testnet-2/0283d0b783c3aa4af7213c06d539dd3ddc2bea4dfc3cae3ab99ff414113023cb7e.json
chore(testnet-2): add xLabs validator info
=> chore(testnet-2): add xLabs validator info

testnet/03480206441052f85a2c4a26a28b198f099755f3fab4ed40d4738596741351f655.json
Validator info for H2O Nodes testnet validator on Monad.
=> Add H2O Nodes validator info

testnet-2/0396fef6759b35b616fa5a63710d6b2ac3226106e8bf02e8d5ae50d480ab3f74bb.json
…74bb.json
add file for starlightnode
=> add file for starlightnode

testnet-2/02d1e8a85c90d37799387cbfe7c53b45f24d4dca5674553bd442f36e45fdbb5b91.json
=> Create P-OPS Team TN-2

testnet-2/03028d2c03fe514d12fe23e830f01ecfb739ab90980c7b3ef3eee983f49f238c3c.json
=> Add NodeStake validator info

testnet-2/0310f7409ed9e903fd461099f6dbcfada946457270f6142d06a3b0c149b8557ce9.json
=> Create info file for Artifact

testnet-2/0304ca6d81817c83b36dbd269f02a93622e8b760721471ede5f402e1b109c72cc9.json
fastproof.xyz is an independent validator run by @hoanhan101. Focused on performance and staying closely involved with the community.
=> Add fastproof.xyz validator info

testnet-2/021ea5834880339fc96383fd49a426643322510792cfc2e89ed73a54efeb6208c5.json
=> add info for Pacific Meta

testnet/03130ed6d4938480d4e271640998959c6ac9b47d0649dbb968e460ebfe39ce25de.json
…25de.json
Add Staking Facilties TN-1
=> Add Staking Facilties TN-1

testnet-2/0347eed30d544b688caa2983831d8ea8a1d563693bc09a775155196040ba392005
Add Grassets Tech validator info
=> Add Grassets Tech validator info

testnet-2/023832733e58e4254b9be31874e24e291b50abb5e0faa7840938deb93575bd15b0.json
=> Validatrium validator info

testnet-2/0301234e6cb806a158d234c1e28de88f9d7b0ab6edb6f3f8b50a0c3db1b7152273.json
=> add cp0x_by_STAKRspace metadata

testnet/038d6f48a936f20a2458f135f54323bcf7a94baf2a7b3b44afed51b3dce1d9f45e.json
Adding SenseiNode validators info file.
=> chore: adding senseinode information to validators testnet-2

testnet-2/0274387058c65eb27d9e28d1df501ccabae92ab4693c47e13b0bb48bfb82b0bef8.json
TBD: confirming the metadata internally, will update soon
=> add aPriori testnet-2 validator info

testnet/02c9cf93d4df1f5c8eba74fead4e252f987d5b8d56b9618b3ef1ce23ae4daa40d9.json
=> conf: add P2P Testnet-1 validator info

testnet-2/03d115b861e0675a0f25ca48720d24ad5e6615a3bdfa2ce8c11b26cf22c32286aa.json
Adding QuantNode validator 03d115b861e0675a0f25ca48720d24ad5e6615a3bdfa2ce8c11b26cf22c32286aa
=> add QuantNode

testnet-2/03b44097ba0b7a92abf1e319665a160126f0efde20da9d4adcceeb56144da00517.json
Add rskl.xyz validator information
=> Add rskl.xyz validator information

testnet-2/026189a9b02971459c0e6081a27e58c2ff5c9c00447e40866b8191048f3fececed.json
=> Add CertHum Info

testnet-2/022bd883feea64dc37b709127340f447d82a45da3b5135b959c7f0ff4d03dddc5e.json
=> update Parsec validator info

testnet-2/03c52a39e091aaa6b46286a1574d81034d80fa5cb90a10acac9cf4c5b394a42b1a.json
Added altlayer validator information
=> Added info for altlayer validator

testnet-2/02c99fd296486c8937ae25af0a91eb9b241d05473858e9c67f59af4faafed0c128.json
=> Add STAKEME operator

testnet-2/029dc4ab4f8de4ca8151c84e8012d6eae3f0bebeb4b3869afa3bd7300169696edb.json
add swissstarnode validator info
=> add swissstarnode

testnet-2/035743107cc10c432c1c120d56c7e6bef665efeee8543b7397f72b7bbfb4e34ee9.json
This PR adds info of Chainsafe as a validator operator for testnet2
=> Add chainsafe operator

testnet-2/029f324664222e59b8f52bd31da650548ed123511065c23a083924aab3db3f14df.json
LakeStake validator info update
=> Validator info

testnet-2/0322b40febf89fa3cf6a05e9bbd8904b1979a0e43814d92de43ecdf81408037423.json, testnet/031b47c2f2b2c6ab5b87cc1ed5120154fc45da33074a1bdf09a05f4a73a27b0269.json
Add Flipside Crypto validator info
=> Add Flipside Crypto validator info

testnet-2/02f575feaf33bd9e0320f807dc6e7a97716822a73636e0530a915e535ca61a2714
=> Update r93ax nodes logo

testnet-2/027f13eb2629c289a4e76d72b6a5fb870753bc5d6f09548be74f42b27b0e0841c4.json
Add Tane network information to testnet-2
=> Add Tane network information to testnet-2

testnet-2/03239c407f1e70d100f2a6c686918bdab3b9b3980b352406ac2216a3eae57e6f20.json
=> Add Validatus validator info

testnet-2/0268adc7c666e36a7deb4581ac401079e921f774b64d67918fdc2e03c50319fbea.json
=> Adding Liquify Info

testnet-2/02a7d18a37da2b3bc1429ef5eb36f5ed584277cac7ff936543c4adc21622283231.json
=> Update TTT VN validator info
